# Generated by Django 4.1.4 on 2023-06-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_rename_category_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='article', max_length=100, verbose_name='Icon'),
        ),
    ]
