# Generated by Django 4.1.4 on 2023-06-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_course_enrolled_alter_course_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='skill', max_length=100, verbose_name='Icon'),
        ),
    ]
