# Generated by Django 4.1.4 on 2023-06-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
        ('classroom', '0006_alter_course_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='modules',
            field=models.ManyToManyField(to='module.module'),
        ),
    ]
